macro(set_default namespace variable)
  if ("${${namespace}_${variable}}" STREQUAL "")
    eval(l_val "${${namespace}_DEFAULT_${variable}}")
    set(${namespace}_${variable} ${l_val})
  endif()
endmacro()

macro(set_default_if_exists namespace variable)
  list(LENGTH ${namespace}_DEFAULT_${variable} l_isList)
  eval(l_val "${${namespace}_DEFAULT_${variable}}")
  if ("${${namespace}_${variable}}" STREQUAL "")
    if (${l_isList} GREATER 1)
      foreach(c_val ${l_val})
        if (EXISTS "${c_val}")
          list(APPEND ${namespace}_${variable} "${c_val}")
        endif()
      endforeach()
    else()
      if (EXISTS "${l_val}")
        set(${namespace}_${variable} ${l_val})
      endif()
    endif()
  endif()
endmacro()
