dist: trusty
cache:
  - apt

install:
  - sudo apt-get install debhelper cmake python-all lintian fakeroot

script:
  - export PATH=/usr/bin:${PATH}
  - dpkg-buildpackage -uc -us
  - lintian ../xtdmake_*.deb
